# Generated by Django 4.1 on 2022-12-08 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gwybodaeth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1023)),
                ('title', models.CharField(max_length=127)),
                ('defs_lang', models.CharField(max_length=8)),
                ('terms_lang', models.CharField(max_length=8)),
                ('terms', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
